# Generated by Django 5.2 on 2025-06-25 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=100)),
                ("release_year", models.PositiveIntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("sci-fi", "Science Fiction"),
                            ("thriller", "Thriller"),
                            ("romance", "Romance"),
                            ("documentary", "Documentary"),
                            ("animation", "Animation"),
                            ("fantasy", "Fantasy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rating from 0.0 to 10.0",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("synopsis", models.TextField(blank=True, max_length=500)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["-release_year", "title"],
            },
        ),
    ]
